### ISSUE TITLE
Add re-rendering in clearUI() to clean all tooltips in current viewport for DisVim.

### ISSUE THREAD

**Issue by sebvu** [sebvu/BD-Plugins#1]
As per [betterdiscord guidelines](https://docs.betterdiscord.app/plugins/basics/creating-a-plugin), cleaning a plugin once it is disabled is essential. 

An issue arises with `BdApi.UI.createTooltip` in which I am unfamiliar with a reliable way to de-render the tooltips upon being disabled. 

See clearUI() function for implementation.

**Comment by bobbyyrice** [comment]
fgggggggffhhh
